/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './menu';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from 'ionic-angular/components/menu/menu';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from 'ionic-angular/components/list/list';
import * as import16 from '@angular/common/src/directives/ng_for';
import * as import17 from 'ionic-angular/components/nav/nav';
import * as import18 from '../../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import19 from 'ionic-angular/components/menu/menu-controller';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/config/config';
import * as import22 from 'ionic-angular/platform/platform';
import * as import23 from 'ionic-angular/util/keyboard';
import * as import24 from '@angular/core/src/zone/ng_zone';
import * as import25 from 'ionic-angular/gestures/gesture-controller';
import * as import26 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from 'ionic-angular/components/tabs/tabs';
import * as import31 from '@angular/core/src/linker/template_ref';
import * as import32 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import33 from '../../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import34 from 'ionic-angular/navigation/nav-controller-base';
import * as import35 from '@angular/core/src/linker/component_factory_resolver';
import * as import36 from 'ionic-angular/transitions/transition-controller';
import * as import37 from 'ionic-angular/navigation/deep-linker';
import * as import38 from 'ionic-angular/components/item/item';
import * as import39 from 'ionic-angular/components/menu/menu-close';
import * as import40 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import41 from 'ionic-angular/util/form';
var renderType_MenuPage_Host:import0.RenderComponentType = (null as any);
class _View_MenuPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MenuPage_0_4:import3.MenuPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MenuPage_Host0,renderType_MenuPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-menu',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MenuPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MenuPage_0_4 = new import3.MenuPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._MenuPage_0_4,[],compView_0);
    compView_0.create(this._MenuPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MenuPage) && (0 === requestNodeIndex))) { return this._MenuPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_MenuPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MenuPage_Host === (null as any))) { (renderType_MenuPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_MenuPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const MenuPageNgFactory:import10.ComponentFactory<import3.MenuPage> = new import10.ComponentFactory<import3.MenuPage>('page-menu',viewFactory_MenuPage_Host0,import3.MenuPage);
const styles_MenuPage:any[] = [];
var renderType_MenuPage:import0.RenderComponentType = (null as any);
class _View_MenuPage0 extends import1.AppView<import3.MenuPage> {
  _viewQuery_content_0:import11.QueryList<any>;
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Menu_0_4:import12.Menu;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Toolbar_2_4:import13.Toolbar;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _Content_5_4:import14.Content;
  _text_6:any;
  _el_7:any;
  _List_7_3:import15.List;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgFor_9_6:import16.NgFor;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Nav_14_4:import17.Nav;
  _text_15:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MenuPage0,renderType_MenuPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_content_0 = new import11.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','navigation');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import18.viewFactory_Menu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Menu_0_4 = new import12.Menu(this.parentInjector.get(import19.MenuController),new import20.ElementRef(this._el_0),this.parentInjector.get(import21.Config),this.parentInjector.get(import22.Platform),this.renderer,this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import24.NgZone),this.parentInjector.get(import25.GestureController));
    this._appEl_0.initComponent(this._Menu_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import26.viewFactory_Toolbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Toolbar_2_4 = new import13.Toolbar(this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import21.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Toolbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Toolbar_2_4,[
      [],
      [],
      [],
      [].concat([this._text_3])
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this._appEl_5 = new import2.AppElement(5,0,this,this._el_5);
    var compView_5:any = import28.viewFactory_Content0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Content_5_4 = new import14.Content(this.parentInjector.get(import21.Config),new import20.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import29.App),this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import24.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import30.Tabs,(null as any)));
    this._appEl_5.initComponent(this._Content_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_7_3 = new import15.List(this.parentInjector.get(import21.Config),new import20.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import25.GestureController));
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import31.TemplateRef_(this._appEl_9,viewFactory_MenuPage1);
    this._NgFor_9_6 = new import16.NgFor(this._appEl_9.vcRef,this._TemplateRef_9_5,this.parentInjector.get(import32.IterableDiffers),this.ref);
    this._text_10 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_5.create(this._Content_5_4,[
      [],
      [].concat([
        this._text_6,
        this._el_7,
        this._text_11
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n',(null as any));
      compView_0.create(this._Menu_0_4,[[].concat([
        this._text_1,
        this._el_2,
        this._text_4,
        this._el_5,
        this._text_12
      ]
    )],(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this._appEl_14 = new import2.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import33.viewFactory_Nav0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Nav_14_4 = new import17.Nav(this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import34.NavControllerBase,(null as any)),this.parentInjector.get(import29.App),this.parentInjector.get(import21.Config),this.parentInjector.get(import23.Keyboard),new import20.ElementRef(this._el_14),this.parentInjector.get(import24.NgZone),this.renderer,this.parentInjector.get(import35.ComponentFactoryResolver),this.parentInjector.get(import25.GestureController),this.parentInjector.get(import36.TransitionController),this.parentInjector.get(import37.DeepLinker,(null as any)));
    this._appEl_14.initComponent(this._Nav_14_4,[],compView_14);
    compView_14.create(this._Nav_14_4,[],(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._viewQuery_content_0.reset([this._Nav_14_4]);
    this.context.content = this._viewQuery_content_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.Toolbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Toolbar_2_4; }
    if (((token === import31.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import16.NgFor) && (9 === requestNodeIndex))) { return this._NgFor_9_6; }
    if (((token === import15.List) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._List_7_3; }
    if (((token === import14.Content) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Content_5_4; }
    if (((token === import12.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Menu_0_4; }
    if (((token === import17.Nav) && (14 === requestNodeIndex))) { return this._Nav_14_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changed = false;
    const currVal_0:any = this._Nav_14_4;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Menu_0_4.content = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Menu_0_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_5_4.ngOnInit(); }
    changes = (null as any);
    const currVal_3:any = this.context.pages;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_9_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_9_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_9_6.ngDoCheck(); }
    const currVal_4:any = this.context.menuRoot;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Nav_14_4.root = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Toolbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_5_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_5,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_14_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_5_4.ngOnDestroy();
    this._Menu_0_4.ngOnDestroy();
  }
}
export function viewFactory_MenuPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MenuPage> {
  if ((renderType_MenuPage === (null as any))) { (renderType_MenuPage = viewUtils.createRenderComponentType('/Users/mhartington/GitHub/StarTrack-Ionic/.tmp/pages/menu/menu.html',0,import9.ViewEncapsulation.None,styles_MenuPage,{})); }
  return new _View_MenuPage0(viewUtils,parentInjector,declarationEl);
}
class _View_MenuPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import38.Item;
  _ItemContent_0_5:import38.ItemContent;
  _MenuClose_0_6:import39.MenuClose;
  _query_Label_0_0:import11.QueryList<any>;
  _query_Button_0_1:import11.QueryList<any>;
  _query_Icon_0_2:import11.QueryList<any>;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MenuPage1,renderType_MenuPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import40.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import38.Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import21.Config),new import20.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import38.ItemContent();
    this._MenuClose_0_6 = new import39.MenuClose(this.parent.parentInjector.get(import19.MenuController));
    this._query_Label_0_0 = new import11.QueryList<any>();
    this._query_Button_0_1 = new import11.QueryList<any>();
    this._query_Icon_0_2 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [],
      [].concat([this._text_1]),
      [],
      []
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import38.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Item_0_4; }
    if (((token === import38.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._ItemContent_0_5; }
    if (((token === import39.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MenuClose_0_6.menuClose = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_3:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MenuPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MenuPage1(viewUtils,parentInjector,declarationEl);
}