/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './favorite';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/content/content';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import14 from 'ionic-angular/config/config';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from 'ionic-angular/components/app/app';
import * as import17 from 'ionic-angular/util/keyboard';
import * as import18 from '@angular/core/src/zone/ng_zone';
import * as import19 from 'ionic-angular/navigation/view-controller';
import * as import20 from 'ionic-angular/components/tabs/tabs';
import * as import21 from 'ionic-angular/components/navbar/navbar';
import * as import22 from 'ionic-angular/components/menu/menu-toggle';
import * as import23 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import24 from '@angular/core/src/linker/query_list';
import * as import25 from 'ionic-angular/components/icon/icon';
import * as import26 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import27 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import28 from 'ionic-angular/components/menu/menu-controller';
import * as import29 from 'ionic-angular/components/toolbar/toolbar';
import * as import30 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
var renderType_FavoritePage_Host:import0.RenderComponentType = (null as any);
class _View_FavoritePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FavoritePage_0_4:import3.FavoritePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FavoritePage_Host0,renderType_FavoritePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-favorite',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FavoritePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FavoritePage_0_4 = new import3.FavoritePage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._FavoritePage_0_4,[],compView_0);
    compView_0.create(this._FavoritePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.FavoritePage) && (0 === requestNodeIndex))) { return this._FavoritePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_FavoritePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_FavoritePage_Host === (null as any))) { (renderType_FavoritePage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_FavoritePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const FavoritePageNgFactory:import10.ComponentFactory<import3.FavoritePage> = new import10.ComponentFactory<import3.FavoritePage>('page-favorite',viewFactory_FavoritePage_Host0,import3.FavoritePage);
const styles_FavoritePage:any[] = [];
var renderType_FavoritePage:import0.RenderComponentType = (null as any);
class _View_FavoritePage0 extends import1.AppView<import3.FavoritePage> {
  _anchor_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TemplateRef_0_4:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Content_2_4:import11.Content;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FavoritePage0,renderType_FavoritePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_4 = new import12.TemplateRef_(this._appEl_0,viewFactory_FavoritePage1);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_2,'light','');
    this._appEl_2 = new import2.AppElement(2,(null as any),this,this._el_2);
    var compView_2:any = import13.viewFactory_Content0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Content_2_4 = new import11.Content(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import16.App),this.parentInjector.get(import17.Keyboard),this.parentInjector.get(import18.NgZone),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import20.Tabs,(null as any)));
    this._appEl_2.initComponent(this._Content_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_2.create(this._Content_2_4,[
      [],
      [].concat([this._text_3]),
      []
    ]
    ,(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._anchor_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_4; }
    if (((token === import11.Content) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Content_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_2_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Content_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Content_2_4.ngOnDestroy();
  }
}
export function viewFactory_FavoritePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.FavoritePage> {
  if ((renderType_FavoritePage === (null as any))) { (renderType_FavoritePage = viewUtils.createRenderComponentType('/Users/mhartington/GitHub/StarTrack-Ionic/.tmp/pages/favorite/favorite.html',0,import9.ViewEncapsulation.None,styles_FavoritePage,{})); }
  return new _View_FavoritePage0(viewUtils,parentInjector,declarationEl);
}
class _View_FavoritePage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Navbar_0_4:import21.Navbar;
  _text_1:any;
  _el_2:any;
  _MenuToggle_2_3:import22.MenuToggle;
  _ToolbarItem_2_4:import23.ToolbarItem;
  _query_Button_2_0:import24.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Icon_4_3:import25.Icon;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _ToolbarTitle_7_4:import26.ToolbarTitle;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FavoritePage1,renderType_FavoritePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','toolbar');
    this.renderer.setElementAttribute(this._el_0,'white','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import27.viewFactory_Navbar0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Navbar_0_4 = new import21.Navbar(this.parentInjector.get(import16.App),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._Navbar_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'menuToggle','');
    this.renderer.setElementAttribute(this._el_2,'secondary','');
    this._MenuToggle_2_3 = new import22.MenuToggle(this.parentInjector.get(import28.MenuController),new import15.ElementRef(this._el_2),this.parentInjector.get(import19.ViewController,(null as any)),this._Navbar_0_4);
    this._ToolbarItem_2_4 = new import23.ToolbarItem(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_0_4);
    this._query_Button_2_0 = new import24.QueryList<any>();
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_4,'name','menu');
    this.renderer.setElementAttribute(this._el_4,'role','img');
    this._Icon_4_3 = new import25.Icon(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_7 = new import2.AppElement(7,0,this,this._el_7);
    var compView_7:any = import30.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(7),this._appEl_7);
    this._ToolbarTitle_7_4 = new import26.ToolbarTitle(this.parentInjector.get(import14.Config),new import15.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_0_4);
    this._appEl_7.initComponent(this._ToolbarTitle_7_4,[],compView_7);
    this._text_8 = this.renderer.createText((null as any),'Favorite',(null as any));
    compView_7.create(this._ToolbarTitle_7_4,[[].concat([this._text_8])],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n',(null as any));
    compView_0.create(this._Navbar_0_4,[
      [].concat([this._el_2]),
      [],
      [],
      [].concat([
        this._text_1,
        this._text_6,
        this._el_7,
        this._text_9
      ]
      )
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.Icon) && (4 === requestNodeIndex))) { return this._Icon_4_3; }
    if (((token === import22.MenuToggle) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MenuToggle_2_3; }
    if (((token === import23.ToolbarItem) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarItem_2_4; }
    if (((token === import26.ToolbarTitle) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarTitle_7_4; }
    if (((token === import21.Navbar) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Navbar_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_2_3.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_4_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_Button_2_0.dirty) {
      this._query_Button_2_0.reset([]);
      this._ToolbarItem_2_4._buttons = this._query_Button_2_0;
      this._query_Button_2_0.notifyOnChanges();
    } }
    const currVal_0:any = this._Navbar_0_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_0_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_2_3.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_4_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_4,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_0_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_4_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_2_3.toggle()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_FavoritePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FavoritePage1(viewUtils,parentInjector,declarationEl);
}