/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './track-detail';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from 'ionic-angular/util/events';
import * as import11 from '../../providers/native-media/native-media';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from 'ionic-angular/components/toolbar/toolbar';
import * as import16 from 'ionic-angular/components/navbar/navbar';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from 'ionic-angular/components/list/list';
import * as import20 from 'ionic-angular/components/card/card';
import * as import21 from 'ionic-angular/components/grid/grid';
import * as import22 from 'ionic-angular/components/fab/fab';
import * as import23 from '@angular/common/src/directives/ng_if';
import * as import24 from 'ionic-angular/components/item/item';
import * as import25 from 'ionic-angular/components/note/note';
import * as import26 from '../../pipes/moment';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import33 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from 'ionic-angular/gestures/gesture-controller';
import * as import38 from '../../node_modules/ionic-angular/components/fab/fab.ngfactory';
import * as import39 from '@angular/core/src/linker/template_ref';
import * as import40 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import41 from 'ionic-angular/util/form';
import * as import42 from '@angular/core/src/security';
import * as import43 from 'ionic-angular/components/icon/icon';
var renderType_TrackDetailPage_Host:import0.RenderComponentType = (null as any);
class _View_TrackDetailPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TrackDetailPage_0_4:import3.TrackDetailPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TrackDetailPage_Host0,renderType_TrackDetailPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-track-detail',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TrackDetailPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TrackDetailPage_0_4 = new import3.TrackDetailPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.Events),this.parentInjector.get(import11.NativeMedia));
    this._appEl_0.initComponent(this._TrackDetailPage_0_4,[],compView_0);
    compView_0.create(this._TrackDetailPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TrackDetailPage) && (0 === requestNodeIndex))) { return this._TrackDetailPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_TrackDetailPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TrackDetailPage_Host === (null as any))) { (renderType_TrackDetailPage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_TrackDetailPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const TrackDetailPageNgFactory:import13.ComponentFactory<import3.TrackDetailPage> = new import13.ComponentFactory<import3.TrackDetailPage>('page-track-detail',viewFactory_TrackDetailPage_Host0,import3.TrackDetailPage);
const styles_TrackDetailPage:any[] = [];
var renderType_TrackDetailPage:import0.RenderComponentType = (null as any);
class _View_TrackDetailPage0 extends import1.AppView<import3.TrackDetailPage> {
  _viewQuery_player_0:import14.QueryList<any>;
  _el_0:any;
  _Header_0_3:import15.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import16.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import17.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import18.Content;
  _text_10:any;
  _el_11:any;
  _List_11_3:import19.List;
  _text_12:any;
  _el_13:any;
  _Card_13_3:import20.Card;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _CardContent_17_3:import20.CardContent;
  _text_18:any;
  _el_19:any;
  _CardTitle_19_3:import20.CardTitle;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _Row_31_3:import21.Row;
  _text_32:any;
  _el_33:any;
  _Col_33_3:import21.Col;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _FabButton_35_4:import22.FabButton;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import23.NgIf;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _TemplateRef_39_5:any;
  _NgIf_39_6:import23.NgIf;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _Col_43_3:import21.Col;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  /*private*/ _appEl_52:import2.AppElement;
  _Item_52_4:import24.Item;
  _ItemContent_52_5:import24.ItemContent;
  _query_Label_52_0:import14.QueryList<any>;
  _query_Button_52_1:import14.QueryList<any>;
  _query_Icon_52_2:import14.QueryList<any>;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _Note_57_3:import25.Note;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  _pipe_moment_0:import26.Moment;
  _pipe_moment_0_0:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TrackDetailPage0,renderType_TrackDetailPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_player_0 = new import14.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import30.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import32.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import17.ToolbarTitle(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import15.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Track Detail',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import33.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import18.Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import36.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_11_3 = new import19.List(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import37.GestureController));
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-card',(null as any));
    this._Card_13_3 = new import20.Card(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'img',(null as any));
    this.renderer.setElementAttribute(this._el_15,'alt','');
    this._text_16 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_13,'ion-card-content',(null as any));
    this._CardContent_17_3 = new import20.CardContent();
    this._text_18 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'ion-card-title',(null as any));
    this._CardTitle_19_3 = new import20.CardTitle();
    this._text_20 = this.renderer.createText(this._el_19,'\n          ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'h2',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_17,'h3',(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_27 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_17,'em',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_17,'\n\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_17,'ion-row',(null as any));
    this._Row_31_3 = new import21.Row();
    this._text_32 = this.renderer.createText(this._el_31,'\n          ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_33,'text-center','');
    this.renderer.setElementAttribute(this._el_33,'width-20','');
    this._Col_33_3 = new import21.Col();
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'button',(null as any));
    this.renderer.setElementAttribute(this._el_35,'color','light');
    this.renderer.setElementAttribute(this._el_35,'ion-fab','');
    this._appEl_35 = new import2.AppElement(35,33,this,this._el_35);
    var compView_35:any = import38.viewFactory_FabButton0(this.viewUtils,this.injector(35),this._appEl_35);
    this._FabButton_35_4 = new import22.FabButton(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_35),this.renderer);
    this._appEl_35.initComponent(this._FabButton_35_4,[],compView_35);
    this._text_36 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_37 = new import2.AppElement(37,35,this,this._anchor_37);
    this._TemplateRef_37_5 = new import39.TemplateRef_(this._appEl_37,viewFactory_TrackDetailPage1);
    this._NgIf_37_6 = new import23.NgIf(this._appEl_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_39 = new import2.AppElement(39,35,this,this._anchor_39);
    this._TemplateRef_39_5 = new import39.TemplateRef_(this._appEl_39,viewFactory_TrackDetailPage2);
    this._NgIf_39_6 = new import23.NgIf(this._appEl_39.vcRef,this._TemplateRef_39_5);
    this._text_40 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_35.create(this._FabButton_35_4,[[].concat([
        this._text_36,
        this._appEl_37,
        this._text_38,
        this._appEl_39,
        this._text_40
      ]
    )],(null as any));
    this._text_41 = this.renderer.createText(this._el_33,'\n          ',(null as any));
    this._text_42 = this.renderer.createText(this._el_31,'\n\n          ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_31,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_43,'width-80','');
    this._Col_43_3 = new import21.Col();
    this._text_44 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'audio',(null as any));
    this._text_46 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_43,'progress',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','progress');
    this.renderer.setElementAttribute(this._el_47,'max','100');
    this._text_48 = this.renderer.createText(this._el_43,'\n          ',(null as any));
    this._text_49 = this.renderer.createText(this._el_31,'\n        ',(null as any));
    this._text_50 = this.renderer.createText(this._el_17,'\n      ',(null as any));
    this._text_51 = this.renderer.createText(this._el_13,'\n\n      ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','item item-block');
    this._appEl_52 = new import2.AppElement(52,13,this,this._el_52);
    var compView_52:any = import40.viewFactory_Item0(this.viewUtils,this.injector(52),this._appEl_52);
    this._Item_52_4 = new import24.Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_52),this.renderer);
    this._ItemContent_52_5 = new import24.ItemContent();
    this._query_Label_52_0 = new import14.QueryList<any>();
    this._query_Button_52_1 = new import14.QueryList<any>();
    this._query_Icon_52_2 = new import14.QueryList<any>();
    this._appEl_52.initComponent(this._Item_52_4,[],compView_52);
    this._text_53 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Track Duration',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_57 = this.renderer.createElement((null as any),'ion-note',(null as any));
    this.renderer.setElementAttribute(this._el_57,'item-right','');
    this._Note_57_3 = new import25.Note();
    this._text_58 = this.renderer.createText(this._el_57,'',(null as any));
    this._text_59 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_52_0.reset([]);
    this._Item_52_4.contentLabel = this._query_Label_52_0.first;
    compView_52.create(this._Item_52_4,[
      [],
      [],
      [].concat([
        this._text_53,
        this._el_54,
        this._text_56,
        this._text_59
      ]
      ),
      [],
      [].concat([this._el_57])
    ]
    ,(null as any));
    this._text_60 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_61 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_62
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_63 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_45,'ended',this.eventHandler(this._handle_ended_45_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_45,'timeupdate',this.eventHandler(this._handle_timeupdate_45_1.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._pipe_moment_0 = new import26.Moment();
    this._pipe_moment_0_0 = import4.pureProxy1(this._pipe_moment_0.transform.bind(this._pipe_moment_0));
    this._expr_15 = import7.UNINITIALIZED;
    this._viewQuery_player_0.reset([new import28.ElementRef(this._el_45)]);
    this.context.audio = this._viewQuery_player_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import16.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import15.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import20.CardTitle) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._CardTitle_19_3; }
    if (((token === import39.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import23.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6; }
    if (((token === import39.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import23.NgIf) && (39 === requestNodeIndex))) { return this._NgIf_39_6; }
    if (((token === import22.FabButton) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._FabButton_35_4; }
    if (((token === import21.Col) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Col_33_3; }
    if (((token === import21.Col) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Col_43_3; }
    if (((token === import21.Row) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Row_31_3; }
    if (((token === import20.CardContent) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._CardContent_17_3; }
    if (((token === import25.Note) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Note_57_3; }
    if (((token === import24.Item) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._Item_52_4; }
    if (((token === import24.ItemContent) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._ItemContent_52_5; }
    if (((token === import20.Card) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Card_13_3; }
    if (((token === import19.List) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._List_11_3; }
    if (((token === import18.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 62)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const valUnwrapper:any = new import7.ValueUnwrapper();
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    changed = false;
    const currVal_8:any = 'light';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._FabButton_35_4.color = currVal_8;
      changed = true;
      this._expr_8 = currVal_8;
    }
    if (changed) { this._appEl_35.componentView.markAsCheckOnce(); }
    const currVal_9:boolean = !this.context.ifPlaying;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_37_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.context.ifPlaying;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_39_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_52_1.dirty) {
        this._query_Button_52_1.reset([]);
        this._Item_52_4._buttons = this._query_Button_52_1;
        this._query_Button_52_1.notifyOnChanges();
      }
      if (this._query_Icon_52_2.dirty) {
        this._query_Icon_52_2.reset([]);
        this._Item_52_4._icons = this._query_Icon_52_2;
        this._query_Icon_52_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_52_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.track.album.images[0].url;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_15,'src',this.viewUtils.sanitizer.sanitize(import42.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.track.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_22,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'by ',this.context.track.artists[0].name,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_26,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.context.track.album.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_29,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_13:any = this.context.track.preview_url;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementProperty(this._el_45,'src',this.viewUtils.sanitizer.sanitize(import42.SecurityContext.URL,currVal_13));
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this.context.progress;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_47,'value',currVal_14);
      this._expr_14 = currVal_14;
    }
    valUnwrapper.reset();
    const currVal_15:any = import4.interpolate(1,'\n          ',valUnwrapper.unwrap(import4.castByValue(this._pipe_moment_0_0,this._pipe_moment_0.transform)(this.context.track.duration_ms)),'\n        ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_15,currVal_15))) {
      this.renderer.setText(this._text_58,currVal_15);
      this._expr_15 = currVal_15;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_click_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.toggleSong()) !== false);
    return (true && pd_0);
  }
  private _handle_ended_45_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.playerEnded()) !== false);
    return (true && pd_0);
  }
  private _handle_timeupdate_45_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.setProgress()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TrackDetailPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.TrackDetailPage> {
  if ((renderType_TrackDetailPage === (null as any))) { (renderType_TrackDetailPage = viewUtils.createRenderComponentType('/Users/mhartington/GitHub/StarTrack-Ionic/.tmp/pages/track-detail/track-detail.html',0,import12.ViewEncapsulation.None,styles_TrackDetailPage,{})); }
  return new _View_TrackDetailPage0(viewUtils,parentInjector,declarationEl);
}
class _View_TrackDetailPage1 extends import1.AppView<any> {
  _el_0:any;
  _Icon_0_3:import43.Icon;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TrackDetailPage1,renderType_TrackDetailPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','secondary');
    this.renderer.setElementAttribute(this._el_0,'name','play');
    this.renderer.setElementAttribute(this._el_0,'role','img');
    this._Icon_0_3 = new import43.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer);
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import43.Icon) && (0 === requestNodeIndex))) { return this._Icon_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Icon_0_3.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'play';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Icon_0_3.name = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._Icon_0_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_0_3.ngOnDestroy();
  }
}
function viewFactory_TrackDetailPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TrackDetailPage1(viewUtils,parentInjector,declarationEl);
}
class _View_TrackDetailPage2 extends import1.AppView<any> {
  _el_0:any;
  _Icon_0_3:import43.Icon;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TrackDetailPage2,renderType_TrackDetailPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','secondary');
    this.renderer.setElementAttribute(this._el_0,'name','square');
    this.renderer.setElementAttribute(this._el_0,'role','img');
    this._Icon_0_3 = new import43.Icon(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer);
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import43.Icon) && (0 === requestNodeIndex))) { return this._Icon_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Icon_0_3.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'square';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Icon_0_3.name = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._Icon_0_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'hide',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_0_3.ngOnDestroy();
  }
}
function viewFactory_TrackDetailPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TrackDetailPage2(viewUtils,parentInjector,declarationEl);
}