/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './search';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from 'ionic-angular/components/toolbar/toolbar';
import * as import13 from 'ionic-angular/components/navbar/navbar';
import * as import14 from 'ionic-angular/components/button/button';
import * as import15 from 'ionic-angular/components/menu/menu-toggle';
import * as import16 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from 'ionic-angular/components/icon/icon';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from 'ionic-angular/components/content/content';
import * as import21 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import22 from '@angular/forms/src/directives/ng_control_status';
import * as import23 from 'ionic-angular/components/list/list';
import * as import24 from 'ionic-angular/components/item/item';
import * as import25 from 'ionic-angular/components/label/label';
import * as import26 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import27 from 'ionic-angular/components/input/input';
import * as import28 from 'ionic-angular/components/radio/radio-group';
import * as import29 from 'ionic-angular/components/list/list-header';
import * as import30 from 'ionic-angular/components/radio/radio-button';
import * as import31 from 'ionic-angular/config/config';
import * as import32 from '@angular/core/src/linker/element_ref';
import * as import33 from 'ionic-angular/navigation/view-controller';
import * as import34 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import35 from 'ionic-angular/components/app/app';
import * as import36 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import37 from 'ionic-angular/components/menu/menu-controller';
import * as import38 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import39 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import40 from 'ionic-angular/util/keyboard';
import * as import41 from '@angular/core/src/zone/ng_zone';
import * as import42 from 'ionic-angular/components/tabs/tabs';
import * as import43 from 'ionic-angular/gestures/gesture-controller';
import * as import44 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import45 from 'ionic-angular/util/form';
import * as import46 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import47 from 'ionic-angular/platform/platform';
import * as import48 from '../../node_modules/ionic-angular/components/radio/radio-button.ngfactory';
import * as import49 from '@angular/forms/src/directives/ng_control';
import * as import50 from '@angular/forms/src/directives/control_value_accessor';
import * as import51 from '@angular/forms/src/directives/control_container';
var renderType_SearchPage_Host:import0.RenderComponentType = (null as any);
class _View_SearchPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SearchPage_0_4:import3.SearchPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchPage_Host0,renderType_SearchPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-search',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SearchPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SearchPage_0_4 = new import3.SearchPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.FormBuilder));
    this._appEl_0.initComponent(this._SearchPage_0_4,[],compView_0);
    compView_0.create(this._SearchPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SearchPage) && (0 === requestNodeIndex))) { return this._SearchPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SearchPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SearchPage_Host === (null as any))) { (renderType_SearchPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_SearchPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SearchPageNgFactory:import11.ComponentFactory<import3.SearchPage> = new import11.ComponentFactory<import3.SearchPage>('page-search',viewFactory_SearchPage_Host0,import3.SearchPage);
const styles_SearchPage:any[] = [];
var renderType_SearchPage:import0.RenderComponentType = (null as any);
class _View_SearchPage0 extends import1.AppView<import3.SearchPage> {
  _el_0:any;
  _Header_0_3:import12.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import13.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import14.Button;
  _MenuToggle_4_5:import15.MenuToggle;
  _ToolbarItem_4_6:import16.ToolbarItem;
  _query_Button_4_0:import17.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import18.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import19.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Content_14_4:import20.Content;
  _text_15:any;
  _el_16:any;
  _FormGroupDirective_16_3:import21.FormGroupDirective;
  _ControlContainer_16_4:any;
  _NgControlStatusGroup_16_5:import22.NgControlStatusGroup;
  _text_17:any;
  _el_18:any;
  _List_18_3:import23.List;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _Item_20_4:import24.Item;
  _ItemContent_20_5:import24.ItemContent;
  _query_Label_20_0:import17.QueryList<any>;
  _query_Button_20_1:import17.QueryList<any>;
  _query_Icon_20_2:import17.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _Label_22_3:import25.Label;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _FormControlName_25_4:import26.FormControlName;
  _NgControl_25_5:any;
  _NgControlStatus_25_6:import22.NgControlStatus;
  _TextInput_25_7:import27.TextInput;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _RadioGroup_29_3:import28.RadioGroup;
  _NG_VALUE_ACCESSOR_29_4:any[];
  _FormControlName_29_5:import26.FormControlName;
  _NgControl_29_6:any;
  _NgControlStatus_29_7:import22.NgControlStatus;
  _List_29_8:import23.List;
  _query_ListHeader_29_0:import17.QueryList<any>;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _Item_31_4:import24.Item;
  _ListHeader_31_5:import29.ListHeader;
  _query_Label_31_0:import17.QueryList<any>;
  _query_Button_31_1:import17.QueryList<any>;
  _query_Icon_31_2:import17.QueryList<any>;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _Item_34_4:import24.Item;
  _ItemContent_34_5:import24.ItemContent;
  _query_Label_34_0:import17.QueryList<any>;
  _query_Button_34_1:import17.QueryList<any>;
  _query_Icon_34_2:import17.QueryList<any>;
  _text_35:any;
  _el_36:any;
  _Label_36_3:import25.Label;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _RadioButton_39_4:import30.RadioButton;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import2.AppElement;
  _Item_42_4:import24.Item;
  _ItemContent_42_5:import24.ItemContent;
  _query_Label_42_0:import17.QueryList<any>;
  _query_Button_42_1:import17.QueryList<any>;
  _query_Icon_42_2:import17.QueryList<any>;
  _text_43:any;
  _el_44:any;
  _Label_44_3:import25.Label;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _RadioButton_47_4:import30.RadioButton;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import2.AppElement;
  _Item_50_4:import24.Item;
  _ItemContent_50_5:import24.ItemContent;
  _query_Label_50_0:import17.QueryList<any>;
  _query_Button_50_1:import17.QueryList<any>;
  _query_Icon_50_2:import17.QueryList<any>;
  _text_51:any;
  _el_52:any;
  _Label_52_3:import25.Label;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  /*private*/ _appEl_55:import2.AppElement;
  _RadioButton_55_4:import30.RadioButton;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  /*private*/ _appEl_58:import2.AppElement;
  _Item_58_4:import24.Item;
  _ItemContent_58_5:import24.ItemContent;
  _query_Label_58_0:import17.QueryList<any>;
  _query_Button_58_1:import17.QueryList<any>;
  _query_Icon_58_2:import17.QueryList<any>;
  _text_59:any;
  _el_60:any;
  _Label_60_3:import25.Label;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  /*private*/ _appEl_63:import2.AppElement;
  _RadioButton_63_4:import30.RadioButton;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  /*private*/ _appEl_69:import2.AppElement;
  _Button_69_4:import14.Button;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SearchPage0,renderType_SearchPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Header(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import33.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import34.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Navbar(this.parentInjector.get(import35.App),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'icon-only','');
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import36.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import14.Button('','',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import15.MenuToggle(this.parentInjector.get(import37.MenuController),new import32.ElementRef(this._el_4),this.parentInjector.get(import33.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import16.ToolbarItem(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import17.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import18.Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import38.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import19.ToolbarTitle(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'Search',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[[].concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._el_4]),
      [],
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import2.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import39.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import20.Content(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import35.App),this.parentInjector.get(import40.Keyboard),this.parentInjector.get(import41.NgZone),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import42.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'form',(null as any));
    this._FormGroupDirective_16_3 = new import21.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_16_4 = this._FormGroupDirective_16_3;
    this._NgControlStatusGroup_16_5 = new import22.NgControlStatusGroup(this._ControlContainer_16_4);
    this._text_17 = this.renderer.createText(this._el_16,'\n\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-list',(null as any));
    this._List_18_3 = new import23.List(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import43.GestureController));
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','item item-block');
    this._appEl_20 = new import2.AppElement(20,18,this,this._el_20);
    var compView_20:any = import44.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import24.Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_20),this.renderer);
    this._ItemContent_20_5 = new import24.ItemContent();
    this._query_Label_20_0 = new import17.QueryList<any>();
    this._query_Button_20_1 = new import17.QueryList<any>();
    this._query_Icon_20_2 = new import17.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4,[],compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_22_3 = new import25.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_22),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Search',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'formControlName','term');
    this.renderer.setElementAttribute(this._el_25,'type','text');
    this._appEl_25 = new import2.AppElement(25,20,this,this._el_25);
    var compView_25:any = import46.viewFactory_TextInput0(this.viewUtils,this.injector(25),this._appEl_25);
    this._FormControlName_25_4 = new import26.FormControlName(this._ControlContainer_16_4,(null as any),(null as any),(null as any));
    this._NgControl_25_5 = this._FormControlName_25_4;
    this._NgControlStatus_25_6 = new import22.NgControlStatus(this._NgControl_25_5);
    this._TextInput_25_7 = new import27.TextInput(this.parentInjector.get(import31.Config),this.parentInjector.get(import45.Form),this._Item_20_4,this.parentInjector.get(import35.App),this.parentInjector.get(import47.Platform),new import32.ElementRef(this._el_25),this.renderer,this._Content_14_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_25_5);
    this._appEl_25.initComponent(this._TextInput_25_7,[],compView_25);
    compView_25.create(this._TextInput_25_7,[],(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_20_0.reset([this._Label_22_3]);
    this._Item_20_4.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4,[
      [],
      [].concat([this._el_22]),
      [].concat([
        this._text_21,
        this._text_24,
        this._text_26
      ]
      ),
      [].concat([this._el_25]),
      []
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_16,'\n\n    ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_16,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_29,'formControlName','filter');
    this.renderer.setElementAttribute(this._el_29,'radio-group','');
    this.renderer.setElementAttribute(this._el_29,'role','radiogroup');
    this._RadioGroup_29_3 = new import28.RadioGroup(this.renderer,new import32.ElementRef(this._el_29));
    this._NG_VALUE_ACCESSOR_29_4 = [this._RadioGroup_29_3];
    this._FormControlName_29_5 = new import26.FormControlName(this._ControlContainer_16_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_29_4);
    this._NgControl_29_6 = this._FormControlName_29_5;
    this._NgControlStatus_29_7 = new import22.NgControlStatus(this._NgControl_29_6);
    this._List_29_8 = new import23.List(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_29),this.renderer,this.parentInjector.get(import43.GestureController));
    this._query_ListHeader_29_0 = new import17.QueryList<any>();
    this._text_30 = this.renderer.createText(this._el_29,'\n      ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','item');
    this._appEl_31 = new import2.AppElement(31,29,this,this._el_31);
    var compView_31:any = import44.viewFactory_Item0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Item_31_4 = new import24.Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_31),this.renderer);
    this._ListHeader_31_5 = new import29.ListHeader(this.parentInjector.get(import31.Config),this.renderer,new import32.ElementRef(this._el_31),(null as any));
    this._query_Label_31_0 = new import17.QueryList<any>();
    this._query_Button_31_1 = new import17.QueryList<any>();
    this._query_Icon_31_2 = new import17.QueryList<any>();
    this._appEl_31.initComponent(this._Item_31_4,[],compView_31);
    this._text_32 = this.renderer.createText((null as any),'\n        Filter\n      ',(null as any));
    this._query_Label_31_0.reset([]);
    this._Item_31_4.contentLabel = this._query_Label_31_0.first;
    compView_31.create(this._Item_31_4,[
      [],
      [],
      [].concat([this._text_32]),
      [],
      []
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n\n      ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_29,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','item item-block');
    this._appEl_34 = new import2.AppElement(34,29,this,this._el_34);
    var compView_34:any = import44.viewFactory_Item0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Item_34_4 = new import24.Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_34),this.renderer);
    this._ItemContent_34_5 = new import24.ItemContent();
    this._query_Label_34_0 = new import17.QueryList<any>();
    this._query_Button_34_1 = new import17.QueryList<any>();
    this._query_Icon_34_2 = new import17.QueryList<any>();
    this._appEl_34.initComponent(this._Item_34_4,[],compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_36_3 = new import25.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_36),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Track Name',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-radio',(null as any));
    this.renderer.setElementAttribute(this._el_39,'color','secondary');
    this.renderer.setElementAttribute(this._el_39,'value','track');
    this._appEl_39 = new import2.AppElement(39,34,this,this._el_39);
    var compView_39:any = import48.viewFactory_RadioButton0(this.viewUtils,this.injector(39),this._appEl_39);
    this._RadioButton_39_4 = new import30.RadioButton(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_39),this.renderer,this._Item_34_4,this._RadioGroup_29_3);
    this._appEl_39.initComponent(this._RadioButton_39_4,[],compView_39);
    compView_39.create(this._RadioButton_39_4,[],(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_34_0.reset([this._Label_36_3]);
    this._Item_34_4.contentLabel = this._query_Label_34_0.first;
    compView_34.create(this._Item_34_4,[
      [],
      [].concat([this._el_36]),
      [].concat([
        this._text_35,
        this._text_38,
        this._text_40
      ]
      ),
      [],
      [].concat([this._el_39])
    ]
    ,(null as any));
    this._text_41 = this.renderer.createText(this._el_29,'\n\n      ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_29,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','item item-block');
    this._appEl_42 = new import2.AppElement(42,29,this,this._el_42);
    var compView_42:any = import44.viewFactory_Item0(this.viewUtils,this.injector(42),this._appEl_42);
    this._Item_42_4 = new import24.Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_42),this.renderer);
    this._ItemContent_42_5 = new import24.ItemContent();
    this._query_Label_42_0 = new import17.QueryList<any>();
    this._query_Button_42_1 = new import17.QueryList<any>();
    this._query_Icon_42_2 = new import17.QueryList<any>();
    this._appEl_42.initComponent(this._Item_42_4,[],compView_42);
    this._text_43 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_44_3 = new import25.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_44),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Artist Name',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'ion-radio',(null as any));
    this.renderer.setElementAttribute(this._el_47,'color','secondary');
    this.renderer.setElementAttribute(this._el_47,'value','artist');
    this._appEl_47 = new import2.AppElement(47,42,this,this._el_47);
    var compView_47:any = import48.viewFactory_RadioButton0(this.viewUtils,this.injector(47),this._appEl_47);
    this._RadioButton_47_4 = new import30.RadioButton(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_47),this.renderer,this._Item_42_4,this._RadioGroup_29_3);
    this._appEl_47.initComponent(this._RadioButton_47_4,[],compView_47);
    compView_47.create(this._RadioButton_47_4,[],(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_42_0.reset([this._Label_44_3]);
    this._Item_42_4.contentLabel = this._query_Label_42_0.first;
    compView_42.create(this._Item_42_4,[
      [],
      [].concat([this._el_44]),
      [].concat([
        this._text_43,
        this._text_46,
        this._text_48
      ]
      ),
      [],
      [].concat([this._el_47])
    ]
    ,(null as any));
    this._text_49 = this.renderer.createText(this._el_29,'\n\n      ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_29,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','item item-block');
    this._appEl_50 = new import2.AppElement(50,29,this,this._el_50);
    var compView_50:any = import44.viewFactory_Item0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Item_50_4 = new import24.Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_50),this.renderer);
    this._ItemContent_50_5 = new import24.ItemContent();
    this._query_Label_50_0 = new import17.QueryList<any>();
    this._query_Button_50_1 = new import17.QueryList<any>();
    this._query_Icon_50_2 = new import17.QueryList<any>();
    this._appEl_50.initComponent(this._Item_50_4,[],compView_50);
    this._text_51 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_52 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_52_3 = new import25.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_52),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Album Name',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-radio',(null as any));
    this.renderer.setElementAttribute(this._el_55,'color','secondary');
    this.renderer.setElementAttribute(this._el_55,'value','album');
    this._appEl_55 = new import2.AppElement(55,50,this,this._el_55);
    var compView_55:any = import48.viewFactory_RadioButton0(this.viewUtils,this.injector(55),this._appEl_55);
    this._RadioButton_55_4 = new import30.RadioButton(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_55),this.renderer,this._Item_50_4,this._RadioGroup_29_3);
    this._appEl_55.initComponent(this._RadioButton_55_4,[],compView_55);
    compView_55.create(this._RadioButton_55_4,[],(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_50_0.reset([this._Label_52_3]);
    this._Item_50_4.contentLabel = this._query_Label_50_0.first;
    compView_50.create(this._Item_50_4,[
      [],
      [].concat([this._el_52]),
      [].concat([
        this._text_51,
        this._text_54,
        this._text_56
      ]
      ),
      [],
      [].concat([this._el_55])
    ]
    ,(null as any));
    this._text_57 = this.renderer.createText(this._el_29,'\n\n      ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_29,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','item item-block');
    this._appEl_58 = new import2.AppElement(58,29,this,this._el_58);
    var compView_58:any = import44.viewFactory_Item0(this.viewUtils,this.injector(58),this._appEl_58);
    this._Item_58_4 = new import24.Item(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_58),this.renderer);
    this._ItemContent_58_5 = new import24.ItemContent();
    this._query_Label_58_0 = new import17.QueryList<any>();
    this._query_Button_58_1 = new import17.QueryList<any>();
    this._query_Icon_58_2 = new import17.QueryList<any>();
    this._appEl_58.initComponent(this._Item_58_4,[],compView_58);
    this._text_59 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_60 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_60_3 = new import25.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_60),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'All of the above',(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_63 = this.renderer.createElement((null as any),'ion-radio',(null as any));
    this.renderer.setElementAttribute(this._el_63,'color','secondary');
    this.renderer.setElementAttribute(this._el_63,'value','everything');
    this._appEl_63 = new import2.AppElement(63,58,this,this._el_63);
    var compView_63:any = import48.viewFactory_RadioButton0(this.viewUtils,this.injector(63),this._appEl_63);
    this._RadioButton_63_4 = new import30.RadioButton(this.parentInjector.get(import45.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_63),this.renderer,this._Item_58_4,this._RadioGroup_29_3);
    this._appEl_63.initComponent(this._RadioButton_63_4,[],compView_63);
    compView_63.create(this._RadioButton_63_4,[],(null as any));
    this._text_64 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_58_0.reset([this._Label_60_3]);
    this._Item_58_4.contentLabel = this._query_Label_58_0.first;
    compView_58.create(this._Item_58_4,[
      [],
      [].concat([this._el_60]),
      [].concat([
        this._text_59,
        this._text_62,
        this._text_64
      ]
      ),
      [],
      [].concat([this._el_63])
    ]
    ,(null as any));
    this._text_65 = this.renderer.createText(this._el_29,'\n\n    ',(null as any));
    this._query_ListHeader_29_0.reset([this._ListHeader_31_5]);
    this._RadioGroup_29_3._header = this._query_ListHeader_29_0.first;
    this._text_66 = this.renderer.createText(this._el_16,'\n\n    ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_67,'padding','');
    this._text_68 = this.renderer.createText(this._el_67,'\n      ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_67,'button',(null as any));
    this.renderer.setElementAttribute(this._el_69,'block','');
    this.renderer.setElementAttribute(this._el_69,'color','secondary');
    this.renderer.setElementAttribute(this._el_69,'ion-button','');
    this.renderer.setElementAttribute(this._el_69,'type','submit');
    this._appEl_69 = new import2.AppElement(69,67,this,this._el_69);
    var compView_69:any = import36.viewFactory_Button0(this.viewUtils,this.injector(69),this._appEl_69);
    this._Button_69_4 = new import14.Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_69),this.renderer);
    this._appEl_69.initComponent(this._Button_69_4,[],compView_69);
    this._text_70 = this.renderer.createText((null as any),'Find Tracks',(null as any));
    compView_69.create(this._Button_69_4,[[].concat([this._text_70])],(null as any));
    this._text_71 = this.renderer.createText(this._el_67,'\n    ',(null as any));
    this._text_72 = this.renderer.createText(this._el_16,'\n\n\n  ',(null as any));
    this._text_73 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4,[
      [],
      [].concat([
        this._text_15,
        this._el_16,
        this._text_73
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_74 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_16,'ngSubmit',this.eventHandler(this._handle_ngSubmit_16_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_16,'submit',this.eventHandler(this._handle_submit_16_1.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_16,'reset',this.eventHandler(this._handle_reset_16_2.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_16_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_16_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_0.bind(this)));
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_55,'click',this.eventHandler(this._handle_click_55_0.bind(this)));
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_63,'click',this.eventHandler(this._handle_click_63_0.bind(this)));
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import14.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import15.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import16.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import19.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import13.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4; }
    if (((token === import12.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3; }
    if (((token === import25.Label) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Label_22_3; }
    if (((token === import26.FormControlName) && (25 === requestNodeIndex))) { return this._FormControlName_25_4; }
    if (((token === import49.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_5; }
    if (((token === import22.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_6; }
    if (((token === import27.TextInput) && (25 === requestNodeIndex))) { return this._TextInput_25_7; }
    if (((token === import24.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_20_4; }
    if (((token === import24.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_20_5; }
    if (((token === import23.List) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._List_18_3; }
    if (((token === import24.Item) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Item_31_4; }
    if (((token === import29.ListHeader) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ListHeader_31_5; }
    if (((token === import25.Label) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Label_36_3; }
    if (((token === import30.RadioButton) && (39 === requestNodeIndex))) { return this._RadioButton_39_4; }
    if (((token === import24.Item) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Item_34_4; }
    if (((token === import24.ItemContent) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ItemContent_34_5; }
    if (((token === import25.Label) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Label_44_3; }
    if (((token === import30.RadioButton) && (47 === requestNodeIndex))) { return this._RadioButton_47_4; }
    if (((token === import24.Item) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Item_42_4; }
    if (((token === import24.ItemContent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._ItemContent_42_5; }
    if (((token === import25.Label) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Label_52_3; }
    if (((token === import30.RadioButton) && (55 === requestNodeIndex))) { return this._RadioButton_55_4; }
    if (((token === import24.Item) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Item_50_4; }
    if (((token === import24.ItemContent) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._ItemContent_50_5; }
    if (((token === import25.Label) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Label_60_3; }
    if (((token === import30.RadioButton) && (63 === requestNodeIndex))) { return this._RadioButton_63_4; }
    if (((token === import24.Item) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Item_58_4; }
    if (((token === import24.ItemContent) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._ItemContent_58_5; }
    if (((token === import28.RadioGroup) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._RadioGroup_29_3; }
    if (((token === import50.NG_VALUE_ACCESSOR) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._NG_VALUE_ACCESSOR_29_4; }
    if (((token === import26.FormControlName) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._FormControlName_29_5; }
    if (((token === import49.NgControl) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._NgControl_29_6; }
    if (((token === import22.NgControlStatus) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._NgControlStatus_29_7; }
    if (((token === import23.List) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._List_29_8; }
    if (((token === import14.Button) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._Button_69_4; }
    if (((token === import21.FormGroupDirective) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._FormGroupDirective_16_3; }
    if (((token === import51.ControlContainer) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._ControlContainer_16_4; }
    if (((token === import22.NgControlStatusGroup) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._NgControlStatusGroup_16_5; }
    if (((token === import20.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Content_14_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_14_4.ngOnInit(); }
    changes = (null as any);
    const currVal_11:any = this.context.form;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._FormGroupDirective_16_3.form = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_16_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_18:any = 'term';
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._FormControlName_25_4.name = currVal_18;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_18,currVal_18);
      this._expr_18 = currVal_18;
    }
    if ((changes !== (null as any))) { this._FormControlName_25_4.ngOnChanges(changes); }
    const currVal_25:any = 'text';
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._TextInput_25_7.type = currVal_25;
      this._expr_25 = currVal_25;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_25_7.ngOnInit(); }
    changes = (null as any);
    const currVal_26:any = 'filter';
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._FormControlName_29_5.name = currVal_26;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_26,currVal_26);
      this._expr_26 = currVal_26;
    }
    if ((changes !== (null as any))) { this._FormControlName_29_5.ngOnChanges(changes); }
    const currVal_34:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._RadioButton_39_4.color = currVal_34;
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = 'track';
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._RadioButton_39_4.value = currVal_35;
      this._expr_35 = currVal_35;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RadioButton_39_4.ngOnInit(); }
    const currVal_38:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this._RadioButton_47_4.color = currVal_38;
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = 'artist';
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this._RadioButton_47_4.value = currVal_39;
      this._expr_39 = currVal_39;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RadioButton_47_4.ngOnInit(); }
    const currVal_42:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this._RadioButton_55_4.color = currVal_42;
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = 'album';
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this._RadioButton_55_4.value = currVal_43;
      this._expr_43 = currVal_43;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RadioButton_55_4.ngOnInit(); }
    const currVal_46:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this._RadioButton_63_4.color = currVal_46;
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = 'everything';
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this._RadioButton_63_4.value = currVal_47;
      this._expr_47 = currVal_47;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RadioButton_63_4.ngOnInit(); }
    changed = false;
    const currVal_50:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this._Button_69_4.block = currVal_50;
      changed = true;
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = 'secondary';
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this._Button_69_4.color = currVal_51;
      changed = true;
      this._expr_51 = currVal_51;
    }
    if (changed) { this._appEl_69.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset([]);
        this._Item_20_4._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset([]);
        this._Item_20_4._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      if (this._query_Button_31_1.dirty) {
        this._query_Button_31_1.reset([]);
        this._Item_31_4._buttons = this._query_Button_31_1;
        this._query_Button_31_1.notifyOnChanges();
      }
      if (this._query_Icon_31_2.dirty) {
        this._query_Icon_31_2.reset([]);
        this._Item_31_4._icons = this._query_Icon_31_2;
        this._query_Icon_31_2.notifyOnChanges();
      }
      if (this._query_Button_34_1.dirty) {
        this._query_Button_34_1.reset([]);
        this._Item_34_4._buttons = this._query_Button_34_1;
        this._query_Button_34_1.notifyOnChanges();
      }
      if (this._query_Icon_34_2.dirty) {
        this._query_Icon_34_2.reset([]);
        this._Item_34_4._icons = this._query_Icon_34_2;
        this._query_Icon_34_2.notifyOnChanges();
      }
      if (this._query_Button_42_1.dirty) {
        this._query_Button_42_1.reset([]);
        this._Item_42_4._buttons = this._query_Button_42_1;
        this._query_Button_42_1.notifyOnChanges();
      }
      if (this._query_Icon_42_2.dirty) {
        this._query_Icon_42_2.reset([]);
        this._Item_42_4._icons = this._query_Icon_42_2;
        this._query_Icon_42_2.notifyOnChanges();
      }
      if (this._query_Button_50_1.dirty) {
        this._query_Button_50_1.reset([]);
        this._Item_50_4._buttons = this._query_Button_50_1;
        this._query_Button_50_1.notifyOnChanges();
      }
      if (this._query_Icon_50_2.dirty) {
        this._query_Icon_50_2.reset([]);
        this._Item_50_4._icons = this._query_Icon_50_2;
        this._query_Icon_50_2.notifyOnChanges();
      }
      if (this._query_Button_58_1.dirty) {
        this._query_Button_58_1.reset([]);
        this._Item_58_4._buttons = this._query_Button_58_1;
        this._query_Button_58_1.notifyOnChanges();
      }
      if (this._query_Icon_58_2.dirty) {
        this._query_Icon_58_2.reset([]);
        this._Item_58_4._icons = this._query_Icon_58_2;
        this._query_Icon_58_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      this._TextInput_25_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_20_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_31_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_34_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_42_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_50_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_58_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RadioGroup_29_3.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_69_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_12:any = this._NgControlStatusGroup_16_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_16,'ng-untouched',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_16_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_16,'ng-touched',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatusGroup_16_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_16,'ng-pristine',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatusGroup_16_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_16,'ng-dirty',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatusGroup_16_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_16,'ng-valid',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatusGroup_16_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_16,'ng-invalid',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_19:any = this._NgControlStatus_25_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_25,'ng-untouched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_25_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_25,'ng-touched',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_25_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_25,'ng-pristine',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_25_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_25,'ng-dirty',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_25_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_25,'ng-valid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_25_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_25,'ng-invalid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = this._NgControlStatus_29_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_29,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_29_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_29,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_29_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_29,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_29_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_29,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_29_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_29,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_29_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_29,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_36:any = this._RadioButton_39_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_39,'radio-disabled',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_40:any = this._RadioButton_47_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_47,'radio-disabled',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_44:any = this._RadioButton_55_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_55,'radio-disabled',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_48:any = this._RadioButton_63_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_63,'radio-disabled',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:boolean = !this.context.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementProperty(this._el_69,'disabled',currVal_49);
      this._expr_49 = currVal_49;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._FormControlName_25_4.ngOnDestroy();
    this._TextInput_25_7.ngOnDestroy();
    this._RadioButton_39_4.ngOnDestroy();
    this._RadioButton_47_4.ngOnDestroy();
    this._RadioButton_55_4.ngOnDestroy();
    this._RadioButton_63_4.ngOnDestroy();
    this._FormControlName_29_5.ngOnDestroy();
    this._Content_14_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_ngSubmit_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.search()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_16_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_16_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_16_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_16_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this._appEl_39.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioButton_39_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_47_0($event:any):boolean {
    this._appEl_47.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioButton_47_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_55_0($event:any):boolean {
    this._appEl_55.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioButton_55_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_63_0($event:any):boolean {
    this._appEl_63.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioButton_63_4._click($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SearchPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SearchPage> {
  if ((renderType_SearchPage === (null as any))) { (renderType_SearchPage = viewUtils.createRenderComponentType('/Users/mhartington/GitHub/StarTrack-Ionic/.tmp/pages/search/search.html',0,import10.ViewEncapsulation.None,styles_SearchPage,{})); }
  return new _View_SearchPage0(viewUtils,parentInjector,declarationEl);
}